# Basics of NumPy array

---

In [1]:
import numpy as np

# tip - The default data type in NumPy is float_.

<font face='georgia'>
    <h2><strong> Creating np array</strong></h2> 

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
type(a)

numpy.ndarray

In [4]:
a = np.array([[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [5]:
b = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
b

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

<font face='georgia'>
    <h2><strong> np array attributes</strong></h2>  
    <ul>
        <li> shape</i></li>
        <li> ndim</li>
        <li> size</li>
        <li> strides</li>
        <li> flags</li> 
        <li> dtype</li>
        <li> T</li>
        <li> flat</li>
    </ul>

In [6]:
# shape - Tuple of array dimensions.

print(a.shape) # row 2, column 3
print(b.shape) # depth 2, row 2, column 3

(2, 3)
(2, 2, 3)


In [7]:
# ndim - Number of array dimensions

print(a.ndim)
print(b.ndim)

2
3


In [8]:
# size - Number of elements in the array

print(a.size)
print(b.size)

6
12


In [9]:
# strides - Tuple of bytes to step in each dimensions when traversing an array.

print(a.strides) # 12 bytes to move to second dimesnsion and 4 bytes to move to next column
print(b.strides)

(12, 4)
(24, 12, 4)


In [10]:
# flags - Information about the memory layout of the array.

print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [11]:
# dtype - Data type of the array elements.

print(a.dtype)
print(b.dtype)

int32
int32


In [12]:
# T - transposed array.

print(a.T)
print('*'*50)
print(b.T)

[[1 1]
 [2 2]
 [3 3]]
**************************************************
[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]


In [13]:
# flat - A 1-D iterator over the array.

print(list(a.flat))
print(list(b.flat))

[1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [14]:
print(a.flat[3])

1


In [15]:
print(type(b.flat))

<class 'numpy.flatiter'>


In [16]:
print(a.flat[[1,4]])
print('*'*50)
a.flat[[1,4]] = 0
print(a)

[2 2]
**************************************************
[[1 0 3]
 [1 0 3]]


In [17]:
a.flat = 5
print(a)

[[5 5 5]
 [5 5 5]]


<font face='georgia'>
    <h3>Functions for creating array</h3>
    <ul>
        <li> zeros</li>
        <li> ones</li>
        <li> empty</li>
        <li> arange</li>
        <li> linspace</li>
        <li> full</li>
    </ul>
        

In [18]:
# zeros - return array of zeros.

np.zeros(2) 

array([0., 0.])

In [19]:
np.zeros((2,2), dtype='int')

array([[0, 0],
       [0, 0]])

In [20]:
# ones - return array of ones.

np.ones(2) 

array([1., 1.])

In [21]:
np.ones((1,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
# empty - return array without initializing entries.

np.empty(3) 

array([6.80273576e-312, 0.00000000e+000, 1.62692081e+219])

In [23]:
np.empty((2,3), dtype='int')

array([[-1795456192,         320,           0],
       [          0,      131074,  1836216174]])

In [24]:
np.empty((3,3), dtype=np.int8) # int16 int32

array([[   0,  120,   72],
       [-106,   64,    1],
       [   0,    0,    0]], dtype=int8)

In [25]:
# arange - return evenly spaced values within a given interval.

np.arange(10) # (start,end,step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [27]:
np.arange(11,1,-2)

array([11,  9,  7,  5,  3])

In [28]:
np.arange(3.0)

array([0., 1., 2.])

In [29]:
np.arange(0, 5, 0.5, dtype=int) # use linspace for this.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
# linspace - return evenly spaced numbers over a specified interval.

np.linspace(1,11) # end is also included

array([ 1.        ,  1.20408163,  1.40816327,  1.6122449 ,  1.81632653,
        2.02040816,  2.2244898 ,  2.42857143,  2.63265306,  2.83673469,
        3.04081633,  3.24489796,  3.44897959,  3.65306122,  3.85714286,
        4.06122449,  4.26530612,  4.46938776,  4.67346939,  4.87755102,
        5.08163265,  5.28571429,  5.48979592,  5.69387755,  5.89795918,
        6.10204082,  6.30612245,  6.51020408,  6.71428571,  6.91836735,
        7.12244898,  7.32653061,  7.53061224,  7.73469388,  7.93877551,
        8.14285714,  8.34693878,  8.55102041,  8.75510204,  8.95918367,
        9.16326531,  9.36734694,  9.57142857,  9.7755102 ,  9.97959184,
       10.18367347, 10.3877551 , 10.59183673, 10.79591837, 11.        ])

In [31]:
np.linspace(1,11,num=5) # num default is 50

array([ 1. ,  3.5,  6. ,  8.5, 11. ])

In [32]:
np.linspace(1,3,5, endpoint=False) # for excluding end

array([1. , 1.4, 1.8, 2.2, 2.6])

In [33]:
np.linspace(1,5,9,retstep=True) # for returning size of spacing between samples.

(array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]), 0.5)

In [34]:
np.linspace([1,2,3],[5,6,7],6)

array([[1. , 2. , 3. ],
       [1.8, 2.8, 3.8],
       [2.6, 3.6, 4.6],
       [3.4, 4.4, 5.4],
       [4.2, 5.2, 6.2],
       [5. , 6. , 7. ]])

In [35]:
np.linspace([1,2,3],[5,6,7],6, axis=-1) # transpose of above result

array([[1. , 1.8, 2.6, 3.4, 4.2, 5. ],
       [2. , 2.8, 3.6, 4.4, 5.2, 6. ],
       [3. , 3.8, 4.6, 5.4, 6.2, 7. ]])

In [36]:
# full - return a new array of given shape and type, filled with given value.

np.full((2,2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [37]:
np.full((3,2), [1,2])

array([[1, 2],
       [1, 2],
       [1, 2]])

In [38]:
np.full((1,2), 10)

array([[10, 10]])

In [39]:
np.full((3,4), 10.)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

<font face='georgia'>
    <h3>Functions for creating diagonal arrays</h3>
    <ul>
        <li> eye</li>
        <li> identity</li>
        <li> diag</li>
        <li> diagflat</li>
    </ul>

In [40]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
np.eye(3, k=1) # 3 rows 4 columns and 1 index of the diagonal. positive k refers to upper diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [43]:
np.eye(3, k=-1) # negative value of k refers to a lower diagonal.

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [44]:
np.eye(4, k=-1, dtype=int)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [45]:
# identity - return the identity array

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [47]:
# diag - Extract a diagonal or construct a diagonal array.

np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
np.diag([1,2], k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [49]:
a = np.arange(1,10).reshape(3,3)
print(a)

np.diag(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [50]:
np.diag(a,k=-1)

array([4, 8])

In [51]:
# diagflat - Create a two-dimensional array with the flattened input as a diagonal.

np.diagflat([3, 2])

array([[3, 0],
       [0, 2]])

In [52]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [53]:
np.diagflat([1,2,3], k=-1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

<font face='georgia'>
    <h2><strong> Manipulating array</strong></h2> 

In [54]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<font face='georgia'>
    <h3>Methods for changing array shape</h3>
    <ul>
        <li> reshape</li>
        <li> flatten</li>
        <li> ravel</li>
    </ul>

In [55]:
# reshape - Gives new shape to an array

a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
a.reshape(-1,2) # it will automatically check the value for row i.e. a.size/2 = 5 as given -1 for row

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [57]:
a.reshape(2,-1) # does not change original array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
print(a)
print('*'*50)
a = a.reshape(2,5)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
**************************************************
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [59]:
# flatten - Return a copy of the array collapsed into one dimension.

a_ = a.flatten()

In [60]:
a[:]=0

In [61]:
print(a_)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[0 0 0 0 0]
 [0 0 0 0 0]]


In [62]:
# ravel - Return a contiguous flattened array. A copy is made only if needed.

a = np.arange(1,11).reshape(2,-1)
a_ = a.ravel()
a_

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
a[:] = 0 # as ravel not always return copy of array so it changes the values in a_ also
print(a_)

[0 0 0 0 0 0 0 0 0 0]


In [64]:
# for viewing flatten array we can use reshape(-1)

a = np.arange(1,11).reshape(2,5)
print(a)
a.reshape(-1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])